apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "olares-app-builder.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "olares-app-builder.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
